"""empty message

Revision ID: 08c5b4124c1d
Revises: 
Create Date: 2017-03-05 23:13:09.685062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08c5b4124c1d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('audit_created_by', sa.Integer(), nullable=True),
    sa.Column('audit_updated_by', sa.Integer(), nullable=True),
    sa.Column('audit_deleted_by', sa.Integer(), nullable=True),
    sa.Column('audit_created_on', sa.DateTime(), nullable=True),
    sa.Column('audit_updated_on', sa.DateTime(), nullable=True),
    sa.Column('audit_deleted_on', sa.DateTime(), nullable=True),
    sa.Column('audit_is_deleted', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('is_suspended', sa.Boolean(), nullable=True),
    sa.Column('credit_limit', sa.Integer(), nullable=True),
    sa.Column('credit_balance', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('audit_created_by', sa.Integer(), nullable=True),
    sa.Column('audit_updated_by', sa.Integer(), nullable=True),
    sa.Column('audit_deleted_by', sa.Integer(), nullable=True),
    sa.Column('audit_created_on', sa.DateTime(), nullable=True),
    sa.Column('audit_updated_on', sa.DateTime(), nullable=True),
    sa.Column('audit_deleted_on', sa.DateTime(), nullable=True),
    sa.Column('audit_is_deleted', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=200), nullable=True),
    sa.Column('email_address', sa.String(length=200), nullable=True),
    sa.Column('hash', sa.String(length=200), nullable=True),
    sa.Column('is_suspended', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('accounts')
    # ### end Alembic commands ###
